apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: default
type: Opaque
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: bW9uZ29sb2NhbHVzZXIK # mongolocaluser
  ME_CONFIG_MONGODB_ADMINPASSWORD: bW9uZ29sb2NhbHBhc3N3b3JkCg== # mongolocalpassword
