apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: default
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: adminer
          image: adminer:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: adminer
      restartPolicy: Always
