apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: default
spec:
  selector:
    app: adminer
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: adminer
      protocol: TCP
      port: 8002
      targetPort: 8080
