@base_endpoint = {{protocol}}://{{auth_host}}
@general_api_route = /general/api/v1
@contentType=application/json

# PING
# @name ping
GET {{base_endpoint}}{{general_api_route}}/ping

###

# Results
# @name get_all_results
GET {{base_endpoint}}{{general_api_route}}/results
Content-Type: {{contentType}}

###
# @name create_result
POST {{base_endpoint}}{{general_api_route}}/results
Content-Type: {{contentType}}

{
  "name": "{{$guid}}"
}

###
# @name get_result
GET {{base_endpoint}}{{general_api_route}}/results/{{create_result.response.body.id}}


###
# @name update_result
PUT {{base_endpoint}}{{general_api_route}}/results/{{create_result.response.body.id}}
Content-Type: {{contentType}}

{
  "name": "updated result"
}


###
# @name delete_result
DELETE {{base_endpoint}}{{general_api_route}}/results/{{create_result.response.body.id}}

