apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
spec:
  selector:
    app: auth
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - name: auth
      protocol: TCP
      port: 8000
      targetPort: 8000
