apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "db"
  labels:
    app: "db"
spec:
  serviceName: "db"
  selector:
    matchLabels:
      app: "db"
  template:
    metadata:
      labels:
        app: "db"
    spec:
      containers:
        - name: db
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
