apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: default
type: Opaque
stringData:
  # Example:
  # password: {{ .Values.password | b64enc }}
  POSTGRES_PASSWORD: auth_db_password
  JWT_SECRET: "467dbde70e7f2c132c311597a86195519b852713d87f9e00bd3509f3ad6b1ce8"
