apiVersion: v1
kind: Service
metadata:
  name: vmp3-mongo
  namespace: default
spec:
  selector:
    app: vmp3-mongo
  type: NodePort
  ports:
    - name: vmp3-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32000
