apiVersion: v1
kind: Secret
metadata:
  name: vmp3-mongo-secret
  namespace: default
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29sb2NhbHVzZXI= # mongolocaluser
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29sb2NhbHBhc3N3b3Jk # mongolocalpassword
  MONGO_USERS_LIST: ZmlsZXNfdXNlcjpkYkFkbWluLHJlYWRXcml0ZTpmaWxlc19wYXNzd29yZA==
