apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: peace2103/vmp3_notification_service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
