from decouple import config


class Config:
    DEBUG = config("DEBUG", default=False, cast=bool)
    SQLALCHEMY_TRACK_MODIFICATIONS = config("SQLALCHEMY_TRACK_MODIFICATIONS", default=False, cast=bool)
    SQLALCHEMY_DATABASE_SCHEMA = config("SQLALCHEMY_DATABASE_SCHEMA")
    SQLALCHEMY_DATABASE_USERNAME = config("SQLALCHEMY_DATABASE_USERNAME")
    SQLALCHEMY_DATABASE_PASSWORD = config("SQLALCHEMY_DATABASE_PASSWORD")
    SQLALCHEMY_DATABASE_HOST = config("SQLALCHEMY_DATABASE_HOST")
    SQLALCHEMY_DATABASE_PORT = config("SQLALCHEMY_DATABASE_PORT")
    SQLALCHEMY_DATABASE_NAME = config("SQLALCHEMY_DATABASE_NAME")
    SQLALCHEMY_DATABASE_URI = f"{SQLALCHEMY_DATABASE_SCHEMA}://{SQLALCHEMY_DATABASE_USERNAME}:{SQLALCHEMY_DATABASE_PASSWORD}@{SQLALCHEMY_DATABASE_HOST}:{SQLALCHEMY_DATABASE_PORT}/{SQLALCHEMY_DATABASE_NAME}"
    JWT_SECRET: str = config("JWT_SECRET", default="")


class DevelopmentConfig(Config):
    DEBUG = True


class ProductionConfig(Config):
    DEBUG = False
