version: '3.8'

volumes:
  postgres_data:


services:
  db:
    image: postgres:13-alpine
    user: postgres:postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ~/pg_backups:/pg_backups

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  auth_web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
