"""empty message

Revision ID: 23adc0fad911
Revises: 288827bcad7a
Create Date: 2022-11-17 02:32:41.586675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23adc0fad911'
down_revision = '288827bcad7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
