"""empty message

Revision ID: 288827bcad7a
Revises: 262cce04d508
Create Date: 2022-11-17 02:31:34.184882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288827bcad7a'
down_revision = '262cce04d508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
