"""empty message

Revision ID: 7b1f7afa3a69
Revises: 6fa923482438
Create Date: 2022-11-16 21:57:51.388570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1f7afa3a69'
down_revision = '6fa923482438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='results_pkey'),
    sa.UniqueConstraint('name', name='results_name_key')
    )
    # ### end Alembic commands ###
